name: 'Release flatpak build'
on:
  push:
    tags: v*
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: de.mediathekview.MediathekView.flatpak
        manifest-path: de.mediathekview.MediathekView.yaml
    - uses: actions/upload-artifact@v3
      with:
        name: de.mediathekview.MediathekView.flatpak
        path: ./de.mediathekview.MediathekView.flatpak
  release:
    runs-on: ubuntu-latest
    needs: flatpak
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: ncipollo/release-action@v1
        with:
          name: 'MediathekView ${{ github.ref_name }}'
          artifacts: "./artifacts/*/*.flatpak"
          token: ${{ secrets.GITHUB_TOKEN }}
